import React from 'react';

const RecentReports = () => {
  const recentReportsData = [
    {
      name: 'Engineering School Q1 Summary',
      type: 'School Performance',
      generatedBy: 'Dr. Sarah Johnson',
      date: 'Dec 15, 2024',
      status: 'completed'
    },
    {
      name: 'Curriculum Approval Timeline',
      type: 'Timeline Analysis',
      generatedBy: 'Admin System',
      date: 'Dec 14, 2024',
      status: 'completed'
    },
    {
      name: 'Monthly QA Compliance',
      type: 'Quality Assurance',
      generatedBy: 'QA Team',
      date: 'Dec 12, 2024',
      status: 'in-progress'
    },
    {
      name: 'CUE Submission Status',
      type: 'External Tracking',
      generatedBy: 'Vice Chancellor Office',
      date: 'Dec 10, 2024',
      status: 'pending'
    }
  ];

  const getStatusDisplay = (status) => {
    const statusMap = {
      'completed': 'Completed',
      'in-progress': 'In Progress',
      'pending': 'Pending'
    };
    return statusMap[status] || status;
  };

  return (
    <div className="report-recent-reports">
      <h2 className="report-recent-reports-title">
        <i className="fas fa-history"></i>
        Recently Generated Reports
      </h2>
      <table className="report-table">
        <thead>
          <tr>
            <th>Report Name</th>
            <th>Type</th>
            <th>Generated By</th>
            <th>Date</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {recentReportsData.map((report, index) => (
            <tr key={index}>
              <td>{report.name}</td>
              <td>{report.type}</td>
              <td>{report.generatedBy}</td>
              <td>{report.date}</td>
              <td>
                <span className={`report-status-badge report-${report.status}`}>
                  {getStatusDisplay(report.status)}
                </span>
              </td>
              <td>
                <button className="report-btn report-btn-outline report-btn-small">
                  <i className={`fas ${report.status === 'completed' ? 'fa-download' : 'fa-eye'}`}></i>
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default RecentReports;